# https://gist.github.com/Klumper/0ad49c0613606b14f1a56551e4a7d737

blueprint:
  name: HomeAssisstant update available notification
  description: Notify user on update availability
  domain: automation
  source_url: https://github.com/bforbenny/HA-Blueprints/blob/master/General/update-notifier.yaml

  # INPUTS
  input:
    updateSensor:
      name: Update Sensor
      description: Sensor which will trigger automation
      selector:
        entity:
          domain: update
    notificationTitle:
      name: Notification Title (optional)
      default: "Upgrade Available!"
    notificationMessage:
      name: Notification Message (optional)
      default: "Home Assisstant {{ newest_version }} is available for download\r\n{{ release_notes }}"
    notifyDevice:
      name: Device(s) to notify
      selector:
        device:
          integration: mobile_app

# TRIGGERS
trigger:
  platform: state
  entity_id: !input updateSensor
  to: "on"

# VARIABLES
variables:
  updater: !input updateSensor
  newest_version: "{{ states[updater].attributes.latest_version }}"
  release_notes: "{{ states[updater].attributes.release_summary }}"
  notify_device: !input notifyDevice
  notification_title: !input notificationTitle
  notification_message: !input notificationMessage

# ACTION
action:
  - alias: "Send companion app notification"
    domain: mobile_app
    type: notify
    device_id: !input notifyDevice
    title: "{{ notification_title }}"
    message: "{{ notification_message }}"
