blueprint:
  name: RDM002 Rotary Dial - Climate
  description: "Expose RDM002 rotary dial to set climate control"
  domain: automation
  input:
    remote:
      name: Philips Hue Tap Dial Switch (RDM002)
      selector:
        device:
          integration: zha
          manufacturer: Signify Netherlands B.V.
          model: RDM002
    HVAC_1:
      name: Climate control
      selector:
        target:
          entity:
            domain: climate
    dial_scale:
      name: Dial Scale
      description: Scale factor for dial turning.
      default: 0.5
      selector:
        number:
          min: 0.1
          max: 5.0
          step: 0.1
  source_url: https://github.com/bforbenny/HA-Blueprints/blob/master/Hue-Tap-Dial/zha-rdm002-dial.yaml
mode: restart
max_exceeded: silent
variables:
  dial_scale: !input "dial_scale"
  HVAC_1: !input "HVAC_1"
  HVAC_1_SP: '{{ state_attr(HVAC_1, "temperature") }}'
trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input "remote"
action:
  - variables:
      command: "{{ trigger.event.data.command }}"
      args: "{{ trigger.event.data.args }}"
      params: "{{ trigger.event.data.params }}"
      scene: "{{ trigger.event.data.params.scene_id }}"
      step_mode: "{{ trigger.event.data.params.step_mode }}"
      step_size: "{{ trigger.event.data.params.step_size }}"
  - choose:
      - conditions:
          - "{{ command == 'step_with_on_off' }}"
          - "{{ step_mode == 'StepMode.Up' }}"
        sequence:
          - service: notify.mobile_app_ben_iphone11
            data:
              message: "{{ HVAC_1_SP + step_size * dial_scale }}"
      - conditions:
          - "{{ command == 'step_with_on_off' }}"
          - "{{ step_mode == 'StepMode.Down' }}"
        sequence:
          - service: notify.mobile_app_ben_iphone11
            data:
              message: "{{ HVAC_1_SP - step_size * dial_scale }}"
